on:
  workflow_call:
jobs:
   create_disks:
    runs-on: ubuntu-latest
    steps:
     - name: 'Checkout'
       uses: actions/checkout@v3
     - name: 'list disks in project'
       run: python3 disks.py '${{ secrets.GCP_PrOJECT_ID}}' -l
