on:
  push:
    branches: [ main ]
jobs:
  check-linting-on-push:
    runs-on: ubuntu-latest
    steps:
     - name: 'Checkout'
       uses: actions/checkout@v3
     - name: 'Install Pylint'
       run: 'sudo apt-get install pylint'
     - name: 'run Pylint'
       run: 'pylint lsp.py'
