on:
  push:
    branches: [ main ]
jobs:
  check-linting-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'Install Pylint'
      - uses: actions/checkout@v3
        run: 'sudo apt-get install pylint'
      - name: 'run Pylint'
      - uses: actions/checkout@v3
        run: 'pylint lsp.py'
